spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=hotel_db
server.port=${PORT:8080}
logging.level.org.springframework=INFO
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
server.tomcat.max-swallow-size=-1

# ===============================
# EMAIL (SENDGRID)
# ===============================
SENDGRID_API_KEY=${SENDGRID_API_KEY}
EMAIL_FROM=${EMAIL_FROM}
OWNER_EMAIL=${OWNER_EMAIL}

# Used in code
app.owner.email=${OWNER_EMAIL}



spring.mvc.media-types.mp4=video/mp4
spring.mvc.media-types.mov=video/quicktime
spring.mvc.media-types.webm=video/webm

imagekit.public-key=${IMAGEKIT_PUBLIC_KEY}
imagekit.private-key=${IMAGEKIT_PRIVATE_KEY}
imagekit.url-endpoint=${IMAGEKIT_URL_ENDPOINT}

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}



